### ISSUE TITLE
Stretching of image

### ISSUE THREAD

**Issue by char1129** [drew0036/confectionery-website-prototype#2]
On Safari iPhone OS 

See photo.
Perhaps width: 100% on img tag and only that would suffice for positioning/scaling of height if not done already?

Great website!!

![DB8FB3E2-F48D-48BF-87D5-F63E1D9F7AAC](https://user-images.githubusercontent.com/55107755/70465929-0a618f00-1a90-11ea-9033-2d47a9146cf6.png)

**Comment by drew0036** [comment]
Thank you! I switched the max-height from 500px to 100%, I think that helped.
